### ISSUE TITLE
Documentation missing about how to actually use fxa-local-dev

### ISSUE THREAD

**Issue by Binarus** [mozilla/fxa-local-dev#98]
At first, many thanks for providing `fxa-local-dev`!

My issue is that I have managed to set up `fxa-local-dev` (this took me two days because I am a NodeJS newbie and a Python newbie and because there are several bugs in the setup scripts), but there seems to be absolutely no documentation about how to actually use it in conjunction with Firefox in production.

As most of us, I do not have the skills to contribute (I would if I could, but NodeJS and Python is not my field), but I would like to synchronize bookmarks and passwords between all clients in my local network (6 client PCs, one Linux and one Windows server) without having to transfer **any** data into the cloud, whether or not that data is encrypted.

In this situation:

**Issue 1: No explanation of how to configure Firefox**

There is no explanation of how to configure Firefox to use it with `fxa-local-dev`.

I solved this problem by installing Firefox into the server where `fxa-local-dev` had been set up, then calling `npm start` which started Firefox with customized settings for usage with `fxa-dev-local` (thanks for making this possible!), then opening `about:config`, searching for settings which had fxa in their name and manually transferring all of them which seemed to be related to sync / accounts to the client PCs, thereby replacing 127.0.0.1 by the FQDN of the server where `fxa-dev-local` was running. That was not funny :-)

Then I changed `public_url` in all json files in `fxa-dev-local` from 127.0.0.1 to the FQDN of the server as well.

That seems to work in the sense that I can now open `http://<FQDN>:3030` from within Firefox on any of the client PCs, and the page which appears then seems to be the right one.

This really should be documented.

**Issue 2: Suspect entries in some JSON (configuration) files in `fxa-local-dev`**

There are still entries in some json files which make me think that data gets transferred into the cloud, and this is the point where I am lost. As an example:

```
nb-www@spock:/install/fxa-local-dev/fxa-content-server/server/config$ cat fxaci.json 
{
  "allowed_parent_origins": ["https://123done-fxaci.dev.lcip.org/"],
  "csp": {
    "enabled": false
  },
  "fxaccount_url": "https://fxaci.dev.lcip.org/auth",
  "oauth_client_id": "ea3ca969f8c6bb0d",
  "oauth_url": "https://oauth-fxaci.dev.lcip.org",
  "profile_images_url": "https://fxaci.dev.lcip.org/profile",
  "profile_url": "https://fxaci.dev.lcip.org/profile",
  "public_url": "http://<FQDN>:3030",
  "use_https": false
}
```

What does that mean? Does `fxa-content-server` connect to something.lcip.org although I have changed all sync / account server entries in `about:config` to the local `fxa-local-dev` server? How do I need to change the json config files to be sure that no external servers are being contacted?

This should be clearly documented.

**Issue 3: HTTP instead of HTTPS is used**

We would like all communication between Firefox and `fxa-local-dev` to take place via HTTPS and not via HTTP, as well as all communication between the various server components. There is no documentation of about how to achieve this.

**Issue 4: All data lost upon server shutdown**

If I got it right (I did not try yet), the database is cleared every time the various servers are stopped; the data seems to be in memory. This might make sense from a developer's point of view, but there are millions of users who want to be able to restart their servers without losing data, or want to backup the data.

I have absolutely no clue how I have to change which server's configuration to make `fxa-local-dev` use a persistent database instead of a memory-based one. So this should be clearly documented as well.

**Epilogue**

Of course, I have read that we shouldn't use `fxa-local-dev` in production.

But the bare truth is that we have to, at least the millions of people and SOHOs who don't want any of their data to leave their own network. There is just no other solution since Mozilla deprecated Weave (which I liked very much because it was simple to set up at the server and the client side).

If you could answer my questions / issues in a way that I understand, I would be willing to contribute to your project by writing a sound tutorial / manual on how to setup `fxa-local-dev` for end users; we could include this as a new section in your `readme.md` or could make it an own document.

If I can't find a solid answer to all of the questions above, I fear I have to abandon the use of Firefox and switch to Chrome and recommend my customers to do the same (Disclaimer: While doing research related to the problems mentioned above, I have read **by accident** that there exists an open source bookmark / password synchronization server for Chrome which could be used locally, **but I did not research this yet and could be completely wrong**).

In any case, the current situation with Firefox is not acceptable any more.

Regards, and thanks for any help,

Binarus

**Comment by Binarus1** [comment]
@vladikoff Thanks for taking the time.

I have understood that you consider this a developer project, so I'll accept that you closed the issue. Nevertheless, I have to state that this is very unsatisfying for various reasons.

Of course, I have thoroughly read the document you linked ("Run your own Sync-1.5 server"). The first question which immediately arises when reading that stuff is: "Why should I run my own Sync server when I still need an external Accounts server?". That does not make any sense in my eyes.

So I have read all documents which are linked from that one, notably the document "Run your own Firefox accounts server".

Although I have been very attentive and careful when following both articles, I did not manage to make the Sync server or the Accounts server work. The articles actually do not explain

- How to make Firefox finally use the servers we have set up that way
- How exactly the Sync server interacts with the Accounts server
- How to secure the communication between those two

From what I have understood from taking a quick look into the json config files, the Sync server will talk to the accounts server using normal http instead of secure https. In fact, I even don't know if Firefox would communicated with the Sync server in a secure way (i.e. encrypted) (if I would have managed to make it work after all).

So here is the only place where we eventually could get these questions answered. Please note that this a thing which does not concern normal users only, but also developers. In fact, I am a developer myself, but in another field until now. I would eventually be interested in participating, but as long as there are absolutely no explanation of how the different components are being meant to work together, I would first have to read and understand the full source code of all servers involved before I even could test the whole thing for the first time.

In general, I have the feeling that Mozilla would like us to believe that they are open minded and protect freedom; therefore, the provide the source code of their Sync and Accounts server software.

But in fact, they are acting like the other big companies and are applying all tricks to force their users to upload every data to their own servers (even if that data is encrypted). Therefore, they only provide the source code, but absolutely not information how to actually use it. The article you linked (and the other articles linked from there) do NOT help anybody because they definitely do not enable us to set up a usable system where Firefox uses internal (own) Sync and Accounts servers only.

As long as Mozilla forces users to synchronize using the Mozilla servers (by not providing information how to configure Firefox and the servers so that they work together as intended), I will dump Mozilla, and I will recommend my clients to do the same.

Regards,

Binarus
